/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GUI;

/**
 *
 * @author Náyron dos Anjos
 */
public class BotaoRadio extends javax.swing.JFrame {

    /**
     * Creates new form BotaoRadio
     */
    public BotaoRadio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jRadioButton500 = new javax.swing.JRadioButton();
        jRadioButton501_1000 = new javax.swing.JRadioButton();
        jRadioButton1001_3000 = new javax.swing.JRadioButton();
        jRadioButton30000 = new javax.swing.JRadioButton();
        Mensagem = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonGroup1.add(jRadioButton500);
        jRadioButton500.setText("Até R$ 500,00");
        jRadioButton500.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton500ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton501_1000);
        jRadioButton501_1000.setText("De R$ 501,00 até R$1000,00");
        jRadioButton501_1000.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton501_1000ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton1001_3000);
        jRadioButton1001_3000.setText("De R$ 1001,00 até R$3000,00");
        jRadioButton1001_3000.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1001_3000ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton30000);
        jRadioButton30000.setText("Acima de R$ 3000,00");
        jRadioButton30000.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton30000ActionPerformed(evt);
            }
        });

        Mensagem.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Mensagem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton1001_3000)
                            .addComponent(jRadioButton501_1000)
                            .addComponent(jRadioButton500)
                            .addComponent(jRadioButton30000))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jRadioButton500)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton501_1000)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton1001_3000)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton30000)
                .addGap(18, 18, 18)
                .addComponent(Mensagem, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton1001_3000ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1001_3000ActionPerformed
        Mensagem.setText("Você não morre mais de fome!");
    }//GEN-LAST:event_jRadioButton1001_3000ActionPerformed

    private void jRadioButton500ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton500ActionPerformed
        Mensagem.setText("Você é pobre!");
    }//GEN-LAST:event_jRadioButton500ActionPerformed

    private void jRadioButton501_1000ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton501_1000ActionPerformed
        Mensagem.setText("É dá para viver alguns dias!");
    }//GEN-LAST:event_jRadioButton501_1000ActionPerformed

    private void jRadioButton30000ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton30000ActionPerformed
        Mensagem.setText("Você já pode tirar um carro!");
    }//GEN-LAST:event_jRadioButton30000ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BotaoRadio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BotaoRadio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BotaoRadio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BotaoRadio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BotaoRadio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Mensagem;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton jRadioButton1001_3000;
    private javax.swing.JRadioButton jRadioButton30000;
    private javax.swing.JRadioButton jRadioButton500;
    private javax.swing.JRadioButton jRadioButton501_1000;
    // End of variables declaration//GEN-END:variables
}
